databases:
  - name: deardiary
    databaseName: deardiary
    user: deardiary
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deardiary
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction